### ISSUE TITLE
Failed to read total coverage

### ISSUE THREAD

**Issue by jkarni** [guillaume-nargeot/hpc-coveralls#45] opened 2015-02-26 16:01 UTC
`hpc-coveralls` sometimes [reports](https://travis-ci.org/haskell-servant/servant/builds/52198675) `Failed to read total coverage`, and the corresponding [page](https://coveralls.io/builds/1998004) on coveralls.io in fact never does display the coverage.

Beyond the logs, I myself really have no insights, unfortunately!

**Comment by guillaume-nargeot** [comment] 2015-02-27 07:50
Thank you for reporting this issue.
I'm going to investigate what's going on.
It may take me a few days until I get back to you as in unsure if I can make time today or this week end, but I will definitely have a look!

**Comment by guillaume-nargeot** [comment] 2015-02-28 03:18
How many times has this happened so far?
From the coveralls list of servant builds, it seems it has only happened once.
There is unfortunately no hint in the travis build logs.
I think it may have been an issue on coveralls side, but don't have any element to prove it...
I've recently improved error handling and reporting in hpc-coveralls, which I should release soon.
This may help to narrow down the cause if it ever happens again.

**Comment by jkarni** [comment] 2015-03-02 14:28
I believe it happened twice. Both times it seems rebuilding fixed it. Maybe the `threadDelay` is too short (or, better yet, it's missing retry logic)?

**Comment by guillaume-nargeot** [comment] 2015-03-25 07:51
The retry logic is already implemented inside the [readCoverageResult function](https://github.com/guillaume-nargeot/hpc-coveralls/blob/f373f417ef895d318448ed1d71e85235bae64f06/src/Trace/Hpc/Coveralls/Curl.hs#L79).
@jkarni I will close this issue for now, but don't hesitate to reopen it if it occurs again.
You can also contact me on gitter if you want!

**Closed** 2015-03-25 07:51 UTC
Labels: bug
